# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
txt="hi there sam!"
x=txt.split()
print(x)

['hi', 'there', 'sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
txt="the diameter of earth is {diameter:.2f} kilometers"
print(txt.format(diameter=12742))

the diameter of earth is 12742.00 kilometers

## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [9]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

## 5. Create an array of all the even integers from 20 to 35

In [10]:
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd

In [14]:
import pandas as pd
dict_a = {
   'col_a':[1,2,3,], 
   'col_b': [4,5,6,], 
}
df = pd.DataFrame(dict_a)
df

   col_a  col_b
0      1      4
1      2      5
2      3      6

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [15]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]